authentications/urls.py
from django.urls import path
from . import views

app_name = 'auth'

urlpatterns = [
    path('', views.login_hendler, name='login'),
    path('signup/', views.signup_hendler, name='signup'),
    path('logout/', views.logout_hendler, name='logout'),
]

ead/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('auth/', include('authentications.urls')),
    path('admin/', admin.site.urls),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

authentications/models.py
from django.db import models

# Create your models here.

class SignupModel(models.Model):
    username = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    password = models.CharField(max_length=255)


    def __str__(self):
        return f"{self.username} | {self.email}"

home/models.py
from django.db import models

# Create your models here.

authentications/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(max_length=255)
    password = forms.CharField(max_length=255, widget=forms.PasswordInput)
    remember = forms.BooleanField(widget=forms.CheckboxInput, required=False)


class SignupForm(forms.Form):
    username = forms.CharField(max_length=255)
    email = forms.CharField(max_length=255, widget=forms.EmailInput)
    password = forms.CharField(max_length=255, widget=forms.PasswordInput)
    check_password = forms.CharField(max_length=255, widget=forms.PasswordInput)

authentications/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from .models import SignupModel
from .forms import LoginForm, SignupForm

# Create your views here.


def login_hendler(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            return redirect('home:index')
        else:
            form = LoginForm(request.GET)
        return render(request, 'login.html', {'form': form})
    else:
        form = LoginForm(request.GET)
    return render(request, 'login.html', {'form': form})


def signup_hendler(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            check_password = form.cleaned_data['check_password']

            if check_password == password:
                SignupModel.objects.create(
                    username = username,
                    email = email,
                    password = password
                )
            else:
                form = SignupForm(request.GET)
                return render(request, 'login.html', {'form': form})
            
            return redirect('auth:login')
        else:
            form = SignupForm(request.GET)
            return render(request, 'signup.html', {'form': form})
    else:
        form = SignupForm(request.GET)
    return render(request, 'signup.html', {'form': form})


def logout_hendler(request):
    print('User logged out')
    return render(request, 'login.html')

home/views.py
from django.shortcuts import render, redirect
from authentications.models import SignupModel

# Create your views here.


def index(request):
    users = SignupModel.objects.all()
    return render(request, 'index.html', {'users': users})

authentications/templates/login.html
{% extends "base.html" %}


{% block content %}
 {% load static %}
    <section class="section forms">
        <figure class="form-side-img">
            <img src="{% static 'images/undraw_code_thinking_re_gka2.svg' %}">
        </figure>
        <form action="" method="post" class="user-form">
            {% csrf_token %}
            <figure class="form-img">
                <img src="{% static 'images/bxs-user-check.svg' %}">
            </figure>
            <input class="user-input" type="text" name="username" placeholder="username" required>
            <input class="user-input" type="password" name="password" placeholder="@Mx13!_s" required>
            <div class="user-options">
                <label for="">
                    <input type="checkbox" name="remember" id=""> Remember Me
                </label>
                <a href="#">Forgot your Password?</a>
            </div>
            <input class="btn submit-btn" type="submit" value="Submit">
            <div class="user-options">
                <p>Don't have an account yet?</p>
                <a class="create-account" href="#">Create here!</a>
            </div>
        </form>

    </section>

{% endblock content %}

authentications/templates/signup.html
{% extends "base.html" %}


{% block content %}
{% load static %}
    <section class="section forms">
        <figure class="form-side-img">
            <img src="{% static 'images/undraw_code_thinking_re_gka2.svg' %}">
        </figure>
        <form action="" method="post" class="user-form">
            {% csrf_token %}
            <figure class="form-img">
                <img src="{% static 'images/bxs-user-check.svg' %}">
            </figure>
            <input class="user-input" type="text" name="username" placeholder="username" required>
            <input class="user-input" type="email" name="email" placeholder="contact@leeva.com" required>
            <input class="user-input" type="password" name="password" placeholder="@Mx13!_s" required>
            <input class="user-input" type="password" name="check_password" placeholder="@Mx13!_s" required>
            <input class="btn submit-btn" type="submit" value="Submit">
            <div class="user-options">
                <p>Alredy have an account?</p>
                <a class="create-account" href="#">Login here!</a>
            </div>
        </form>

    </section>

{% endblock content %}

home/templates/index.html
{% extends "base.html" %}



{% block content %}
    
{% load static %}

<div class="content-wrap">
    <!-- DISPLAY CARDS -->
    <div>
        <section class="section card-wrapper  card-section">
            <div class="wrapper">
                <div class="section-header">
                    <h1>Learn how to code with our latest courses</h1>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus nulla maiores sequi nam illum obcaecati placeat, tempore a corporis quasi esse aliquam fugit sed iste.</p>
                </div>
                
                <div class="inner-wrapper">
                    {% for user in users %}
                        <div class="card">
                            <figure class="card-img-frame">
                                <img src="{% static 'images/undraw_annotation_re_h774.svg' %}">
                            </figure>
                            <h3>{{user.username}}</h3>
                            <div class="card-on-hover">
                                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. 
                                Ad unde molestias accusantium? Ab vitae expedita iure placeat, 
                                eaque quod consequuntur dolore accusantium obcaecati illo alias.</p>
                                <a href="#" class="btn sign-up">Start Now</a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>        
        </section>
    </div>

    <!-- DISPLAY FORMS -->


    <!-- <nav class="side-menu">
        <ul>
            <li><a href="#">Topic</a></li>
            <li><a href="#">Topic</a></li>
            <li><a href="#">Topic</a></li>
            <li><a href="#">Topic</a></li>
            <li><a href="#">Topic</a></li>
        </ul>
    </nav> -->

</div>


{% endblock content %}
    

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
    
    <header class="main-header">
        <nav class="main-nav size-controler">
            
            <a href="{% url 'home:index' %}" class="logo">leeva.inc</a>
            <ul class="main-menu">
                <li><a href="#">How to</a></li>
                <li><a href="#">Free Courses</a></li>
            </ul>
            <ul class="user-menu">
                <li><a class="btn login" href="{% url 'auth:login' %}">Log in</a></li>
                <li><a class="btn sign-up" href="{% url 'auth:signup' %}">Sign up</a></li>
            </ul>
            <div class="toggle">
                <div></div>
                <div></div>
                <div></div>
            </div>
        </nav>
    </header>


<div class="main-container">



    <div class="size-controler">

        {% block content %}
          
        {% endblock content %}


        

    </div>

  
    
</div>

<!-- <figure class="card-img">
    <img src="../images/undraw_freelancer_re_irh4.svg" alt="" srcset="">
</figure> -->

<!-- FOOTER -->



</body>
</html>